apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: staging
  app.kubernetes.io/managed-by: kustomize

resources:
- ../../base

patchesStrategicMerge:
- webapp.yaml
- route.yaml
