ci_cd_namespace: &ci_cd "sample-deployment-ci-cd"
dev_namespace: &dev "sample-deployment-dev"
test_namespace: &test "sample-deployment-test"
staging_namespace: &stage "sample-deployment-staging"

# App of applications list
applications:

  # Jenkins
  - name: jenkins
    enabled: false
    destination: "openshift-gitops"
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-1.0.7"
    values:
      persistence: false
      source_secrets:
        - name: nexus-password
          username: admin
          password: admin123

  # Nexus
  - name: nexus
    enabled: true
    destination: "sample-deployment-ci-cd"
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_ref: "1.1.4"
    values:
      service:
        name: nexus

  # Sealed Secrets Controller
  # Note you can only have one of these per cluster so be careful 
  - name: sealed-secrets-controller
    enabled: false
    chart_name: sealed-secrets
    source: https://bitnami-labs.github.io/sealed-secrets
    source_ref: "2.1.6"
    values:
      nameOverride: sealed-secrets
      fullnameOverride: sealed-secrets
      # namespace must exist, so we use labs-ci-cd by default.
      namespace: *ci_cd
      # Dont touch the security context values, deployment will fail in OpenShift otherwise.
      podSecurityContext:
        fsGroup:
      containerSecurityContext:
        runAsUser:
      commandArgs:
        - "--update-status=true"

  # Sonarqube
  - name: sonarqube
    enabled: false
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonarqube
    source_ref: "0.1.0"
    values:
      # if integrating into an existing sealed secret or other cluster secret 
      # account:
      #   existingSecret: sonarqube-auth
      initContainers: true
      plugins:
        install:
          - https://github.com/checkstyle/sonar-checkstyle/releases/download/8.40/checkstyle-sonar-plugin-8.40.jar
          - https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar

  # Zalenium
  - name: zalenium
    enabled: false
    source: https://github.com/zalando/zalenium.git
    source_path: charts/zalenium
    source_ref: "master"
    values:
      hub:
        serviceType: ClusterIP
        openshift:
          deploymentConfig:
            enabled: true
          route:
            enabled: true
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
        persistence:
          enabled: false
        serviceAccount:
          create: false
        desiredContainers: 0
        podAnnotations:
          app: zalenium

  # Pact-broker
  - name: pact-broker
    enabled: false
    source: https://redhat-cop.github.io/helm-charts
    source_ref: "0.0.8"
    values:
      # update the passwords :)
 
   # Hoverfly
  - name: hoverfly
    enabled: false
    source: https://github.com/helm/charts.git
    source_path: incubator/hoverfly
    source_ref: "master"
    values:
      image:
        tag: v1.3.3
      openshift:
        route:
          admin:
            enabled: true
            hostname: ''
          proxy:
            enabled: true
            hostname: ''
