applications:

  ################################################
  # Operator Installer
  ################################################
  - name: operators-installer
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: "main"
    values:
     installPlanApproverAndVerifyJobsImage: registry.redhat.io/openshift4/ose-cli:v4.10@sha256:7804ea66ea8ca0f414148b8b3b52ae454800785e80a32bd8a5eb2db789014a00

     operators:
       - name: rhacs-operator
         channel: rhacs-4.4
         csv: rhacs-operator.v4.4.0
         source: redhat-operators
         sourceNamespace: openshift-marketplace
         installPlanApproval: Automatic
         namespace: rhacs-operator

       - name: quay-operator
         channel: stable-3.11
         csv: quay-operator.v3.11.0
         source: redhat-operators
         sourceNamespace: openshift-marketplace
         installPlanApproval: Automatic
         namespace: openshift-operators

#      - channel: gitops-1.12
#        installPlanApproval: Manual
#        name: openshift-gitops-operator
#        source: redhat-operators
#        sourceNamespace: openshift-marketplace
#        csv: openshift-gitops-operator.v1.12.0
#        namespace: openshift-gitops-operator



  ################################################
  # Quay Instance
  ################################################
  - name: quay
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/quay
    source_ref: "main"
    values:
      infra_nodes: false
      quay_registry_config_bundle:
        # REGISTRY_TITLE: My Awesome Quay
        # add your configuration fields here
      registry_components:
        - kind: clair
          managed: true
        - kind: postgres
          managed: true
        - kind: objectstorage
          managed: true
        - kind: redis
          managed: true
        - kind: horizontalpodautoscaler
          managed: true
        - kind: route
          managed: true
        - kind: mirror
          managed: true
        - kind: monitoring
          managed: true
        - kind: tls
          managed: true
        - kind: quay
          managed: true
        - kind: clairpostgres
          managed: true

  ################################################
  # ACS Central
  ################################################
  - name: acs
    enabled: true
    source: https://mirror.openshift.com/pub/rhacs/charts/
    chart_name: rhacs/central-services
    source_ref: "400.4.0"
    destination: "rhacs-operator"
