applications:

  # Quay
  - name: quay
    enabled: false
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/quay
    source_ref: "main"
    values:
      infra_nodes: false
      quay_registry_config_bundle:
        # REGISTRY_TITLE: My Awesome Quay
        # add your configuration fields here
      registry_components:
        - kind: clair
          managed: true
        - kind: postgres
          managed: true
        - kind: objectstorage
          managed: true
        - kind: redis
          managed: true
        - kind: horizontalpodautoscaler
          managed: true
        - kind: route
          managed: true
        - kind: mirror
          managed: true
        - kind: monitoring
          managed: true
        - kind: tls
          managed: true
        - kind: quay
          managed: true
        - kind: clairpostgres
